//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_Client_WF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="Web Services", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="My first web serviceSoap", Namespace="Web Services", ConfigurationName="ServiceReference1.MyfirstwebserviceSoap")]
    public interface MyfirstwebserviceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace Web Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/HelloWorld", ReplyAction="*")]
        Lab4_Client_WF.ServiceReference1.HelloWorldResponse HelloWorld(Lab4_Client_WF.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Lab4_Client_WF.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/FtoC", ReplyAction="*")]
        double FtoC(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/FtoC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FtoCAsync(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/CtoF", ReplyAction="*")]
        double CtoF(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/CtoF", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CtoFAsync(double x);
        
        // CODEGEN: Generating message contract since element name ShowDateAndTimeResult from namespace Web Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ShowDateAndTime", ReplyAction="*")]
        Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse ShowDateAndTime(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ShowDateAndTime", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse> ShowDateAndTimeAsync(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ConvertToEuro", ReplyAction="*")]
        double ConvertToEuro(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ConvertToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConvertToEuroAsync(double x);
        
        // CODEGEN: Generating message contract since element name ShowListResult from namespace Web Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ShowList", ReplyAction="*")]
        Lab4_Client_WF.ServiceReference1.ShowListResponse ShowList(Lab4_Client_WF.ServiceReference1.ShowListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/ShowList", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowListResponse> ShowListAsync(Lab4_Client_WF.ServiceReference1.ShowListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab4_Client_WF.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab4_Client_WF.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Web Services")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowDateAndTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowDateAndTime", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequestBody Body;
        
        public ShowDateAndTimeRequest() {
        }
        
        public ShowDateAndTimeRequest(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowDateAndTimeRequestBody {
        
        public ShowDateAndTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowDateAndTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowDateAndTimeResponse", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponseBody Body;
        
        public ShowDateAndTimeResponse() {
        }
        
        public ShowDateAndTimeResponse(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Web Services")]
    public partial class ShowDateAndTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowDateAndTimeResult;
        
        public ShowDateAndTimeResponseBody() {
        }
        
        public ShowDateAndTimeResponseBody(string ShowDateAndTimeResult) {
            this.ShowDateAndTimeResult = ShowDateAndTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowList", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.ShowListRequestBody Body;
        
        public ShowListRequest() {
        }
        
        public ShowListRequest(Lab4_Client_WF.ServiceReference1.ShowListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowListRequestBody {
        
        public ShowListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowListResponse", Namespace="Web Services", Order=0)]
        public Lab4_Client_WF.ServiceReference1.ShowListResponseBody Body;
        
        public ShowListResponse() {
        }
        
        public ShowListResponse(Lab4_Client_WF.ServiceReference1.ShowListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Web Services")]
    public partial class ShowListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab4_Client_WF.ServiceReference1.ArrayOfString ShowListResult;
        
        public ShowListResponseBody() {
        }
        
        public ShowListResponseBody(Lab4_Client_WF.ServiceReference1.ArrayOfString ShowListResult) {
            this.ShowListResult = ShowListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyfirstwebserviceSoapChannel : Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyfirstwebserviceSoapClient : System.ServiceModel.ClientBase<Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap>, Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap {
        
        public MyfirstwebserviceSoapClient() {
        }
        
        public MyfirstwebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyfirstwebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyfirstwebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyfirstwebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client_WF.ServiceReference1.HelloWorldResponse Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.HelloWorld(Lab4_Client_WF.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab4_Client_WF.ServiceReference1.HelloWorldRequest inValue = new Lab4_Client_WF.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.HelloWorldRequestBody();
            Lab4_Client_WF.ServiceReference1.HelloWorldResponse retVal = ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.HelloWorldResponse> Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.HelloWorldAsync(Lab4_Client_WF.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Lab4_Client_WF.ServiceReference1.HelloWorldRequest inValue = new Lab4_Client_WF.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.HelloWorldRequestBody();
            return ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double FtoC(double x) {
            return base.Channel.FtoC(x);
        }
        
        public System.Threading.Tasks.Task<double> FtoCAsync(double x) {
            return base.Channel.FtoCAsync(x);
        }
        
        public double CtoF(double x) {
            return base.Channel.CtoF(x);
        }
        
        public System.Threading.Tasks.Task<double> CtoFAsync(double x) {
            return base.Channel.CtoFAsync(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.ShowDateAndTime(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest request) {
            return base.Channel.ShowDateAndTime(request);
        }
        
        public string ShowDateAndTime() {
            Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest inValue = new Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequestBody();
            Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse retVal = ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).ShowDateAndTime(inValue);
            return retVal.Body.ShowDateAndTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse> Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.ShowDateAndTimeAsync(Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest request) {
            return base.Channel.ShowDateAndTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowDateAndTimeResponse> ShowDateAndTimeAsync() {
            Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest inValue = new Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.ShowDateAndTimeRequestBody();
            return ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).ShowDateAndTimeAsync(inValue);
        }
        
        public double ConvertToEuro(double x) {
            return base.Channel.ConvertToEuro(x);
        }
        
        public System.Threading.Tasks.Task<double> ConvertToEuroAsync(double x) {
            return base.Channel.ConvertToEuroAsync(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client_WF.ServiceReference1.ShowListResponse Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.ShowList(Lab4_Client_WF.ServiceReference1.ShowListRequest request) {
            return base.Channel.ShowList(request);
        }
        
        public Lab4_Client_WF.ServiceReference1.ArrayOfString ShowList() {
            Lab4_Client_WF.ServiceReference1.ShowListRequest inValue = new Lab4_Client_WF.ServiceReference1.ShowListRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.ShowListRequestBody();
            Lab4_Client_WF.ServiceReference1.ShowListResponse retVal = ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).ShowList(inValue);
            return retVal.Body.ShowListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowListResponse> Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap.ShowListAsync(Lab4_Client_WF.ServiceReference1.ShowListRequest request) {
            return base.Channel.ShowListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client_WF.ServiceReference1.ShowListResponse> ShowListAsync() {
            Lab4_Client_WF.ServiceReference1.ShowListRequest inValue = new Lab4_Client_WF.ServiceReference1.ShowListRequest();
            inValue.Body = new Lab4_Client_WF.ServiceReference1.ShowListRequestBody();
            return ((Lab4_Client_WF.ServiceReference1.MyfirstwebserviceSoap)(this)).ShowListAsync(inValue);
        }
    }
}
